name: CI
on: [push]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip
      - run: python -m unittest discover src.tests
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip
      - run: pip install pylint
      - run: pylint $(find -type f -name "*.py" ! -path "**/.venv/**")
